// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: auth/events.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthEvent is every message on the auth.events topic. The message key is
// the user id, so one user's events stay in order.
type AuthEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique per event; consumers use it to skip events they already handled,
	// since Kafka can deliver a message more than once.
	EventId    string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AuthEvent_IdentityRegistered
	Payload       isAuthEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEvent) Reset() {
	*x = AuthEvent{}
	mi := &file_auth_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEvent) ProtoMessage() {}

func (x *AuthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_auth_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEvent.ProtoReflect.Descriptor instead.
func (*AuthEvent) Descriptor() ([]byte, []int) {
	return file_auth_events_proto_rawDescGZIP(), []int{0}
}

func (x *AuthEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AuthEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AuthEvent) GetPayload() isAuthEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthEvent) GetIdentityRegistered() *IdentityRegistered {
	if x != nil {
		if x, ok := x.Payload.(*AuthEvent_IdentityRegistered); ok {
			return x.IdentityRegistered
		}
	}
	return nil
}

type isAuthEvent_Payload interface {
	isAuthEvent_Payload()
}

type AuthEvent_IdentityRegistered struct {
	IdentityRegistered *IdentityRegistered `protobuf:"bytes,10,opt,name=identity_registered,json=identityRegistered,proto3,oneof"`
}

func (*AuthEvent_IdentityRegistered) isAuthEvent_Payload() {}

// IdentityRegistered: someone registered. The user-service creates the
// profile under user_id, which the auth-service generated.
type IdentityRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRegistered) Reset() {
	*x = IdentityRegistered{}
	mi := &file_auth_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRegistered) ProtoMessage() {}

func (x *IdentityRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_auth_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRegistered.ProtoReflect.Descriptor instead.
func (*IdentityRegistered) Descriptor() ([]byte, []int) {
	return file_auth_events_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityRegistered) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IdentityRegistered) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IdentityRegistered) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *IdentityRegistered) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *IdentityRegistered) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

var File_auth_events_proto protoreflect.FileDescriptor

const file_auth_events_proto_rawDesc = "" +
	"\n" +
	"\x11auth/events.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\tAuthEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12K\n" +
	"\x13identity_registered\x18\n" +
	" \x01(\v2\x18.auth.IdentityRegisteredH\x00R\x12identityRegisteredB\t\n" +
	"\apayload\"\xa4\x01\n" +
	"\x12IdentityRegistered\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x00R\x05phone\x88\x01\x01B\b\n" +
	"\x06_phoneb\x06proto3"

var (
	file_auth_events_proto_rawDescOnce sync.Once
	file_auth_events_proto_rawDescData []byte
)

func file_auth_events_proto_rawDescGZIP() []byte {
	file_auth_events_proto_rawDescOnce.Do(func() {
		file_auth_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_events_proto_rawDesc), len(file_auth_events_proto_rawDesc)))
	})
	return file_auth_events_proto_rawDescData
}

var file_auth_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_events_proto_goTypes = []any{
	(*AuthEvent)(nil),             // 0: auth.AuthEvent
	(*IdentityRegistered)(nil),    // 1: auth.IdentityRegistered
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_auth_events_proto_depIdxs = []int32{
	2, // 0: auth.AuthEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: auth.AuthEvent.identity_registered:type_name -> auth.IdentityRegistered
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_events_proto_init() }
func file_auth_events_proto_init() {
	if File_auth_events_proto != nil {
		return
	}
	file_auth_events_proto_msgTypes[0].OneofWrappers = []any{
		(*AuthEvent_IdentityRegistered)(nil),
	}
	file_auth_events_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_events_proto_rawDesc), len(file_auth_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_events_proto_goTypes,
		DependencyIndexes: file_auth_events_proto_depIdxs,
		MessageInfos:      file_auth_events_proto_msgTypes,
	}.Build()
	File_auth_events_proto = out.File
	file_auth_events_proto_goTypes = nil
	file_auth_events_proto_depIdxs = nil
}
