// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: item/item.proto

package itempb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// KSUID: 27 base62 characters.
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_item_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ItemStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStatus) Reset() {
	*x = ItemStatus{}
	mi := &file_item_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStatus) ProtoMessage() {}

func (x *ItemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStatus.ProtoReflect.Descriptor instead.
func (*ItemStatus) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ItemStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	StatusId      string                 `protobuf:"bytes,6,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	Category      *Category              `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Status        *ItemStatus            `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_item_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Item) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *Item) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Item) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

func (x *Item) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Item) GetStatus() *ItemStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// An item's editable fields, to create one and to replace one on update.
type ItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageUrl      *string                `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	StatusId      string                 `protobuf:"bytes,5,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInput) Reset() {
	*x = ItemInput{}
	mi := &file_item_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInput) ProtoMessage() {}

func (x *ItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInput.ProtoReflect.Descriptor instead.
func (*ItemInput) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{3}
}

func (x *ItemInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemInput) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ItemInput) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *ItemInput) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ItemInput) GetStatusId() string {
	if x != nil {
		return x.StatusId
	}
	return ""
}

type ItemFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches the name or the description.
	Search *string `protobuf:"bytes,1,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Name   *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Exact matches.
	CategoryId    *string `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	StatusId      *string `protobuf:"bytes,4,opt,name=status_id,json=statusId,proto3,oneof" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemFilter) Reset() {
	*x = ItemFilter{}
	mi := &file_item_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemFilter) ProtoMessage() {}

func (x *ItemFilter) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemFilter.ProtoReflect.Descriptor instead.
func (*ItemFilter) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{4}
}

func (x *ItemFilter) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *ItemFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ItemFilter) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *ItemFilter) GetStatusId() string {
	if x != nil && x.StatusId != nil {
		return *x.StatusId
	}
	return ""
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_item_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_item_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{6}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListItemsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Offset int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// name, category_id, status_id, created_at or updated_at.
	OrderBy       string      `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	SortDirection string      `protobuf:"bytes,4,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"`
	Filter        *ItemFilter `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_item_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{7}
}

func (x *ListItemsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListItemsRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

func (x *ListItemsRequest) GetFilter() *ItemFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_item_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{8}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ItemInput             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_item_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{9}
}

func (x *CreateItemRequest) GetItem() *ItemInput {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_item_item_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{10}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Item          *ItemInput             `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_item_item_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetItem() *ItemInput {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_item_item_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_item_item_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_item_item_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{14}
}

// Filters categories or statuses.
type NameFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        *string                `protobuf:"bytes,1,opt,name=search,proto3,oneof" json:"search,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameFilter) Reset() {
	*x = NameFilter{}
	mi := &file_item_item_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameFilter) ProtoMessage() {}

func (x *NameFilter) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameFilter.ProtoReflect.Descriptor instead.
func (*NameFilter) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{15}
}

func (x *NameFilter) GetSearch() string {
	if x != nil && x.Search != nil {
		return *x.Search
	}
	return ""
}

func (x *NameFilter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ListCategoriesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Offset int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// name, created_at or updated_at.
	OrderBy       string      `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	SortDirection string      `protobuf:"bytes,4,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"`
	Filter        *NameFilter `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_item_item_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{16}
}

func (x *ListCategoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCategoriesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListCategoriesRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

func (x *ListCategoriesRequest) GetFilter() *NameFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_item_item_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{17}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListCategoriesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_item_item_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_item_item_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{19}
}

func (x *CreateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_item_item_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_item_item_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_item_item_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_item_item_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{23}
}

type ListItemStatusesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Offset int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// name, created_at or updated_at.
	OrderBy       string      `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	SortDirection string      `protobuf:"bytes,4,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"`
	Filter        *NameFilter `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemStatusesRequest) Reset() {
	*x = ListItemStatusesRequest{}
	mi := &file_item_item_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemStatusesRequest) ProtoMessage() {}

func (x *ListItemStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemStatusesRequest.ProtoReflect.Descriptor instead.
func (*ListItemStatusesRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{24}
}

func (x *ListItemStatusesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListItemStatusesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemStatusesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListItemStatusesRequest) GetSortDirection() string {
	if x != nil {
		return x.SortDirection
	}
	return ""
}

func (x *ListItemStatusesRequest) GetFilter() *NameFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListItemStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ItemStatus          `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemStatusesResponse) Reset() {
	*x = ListItemStatusesResponse{}
	mi := &file_item_item_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemStatusesResponse) ProtoMessage() {}

func (x *ListItemStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemStatusesResponse.ProtoReflect.Descriptor instead.
func (*ListItemStatusesResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{25}
}

func (x *ListItemStatusesResponse) GetStatuses() []*ItemStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListItemStatusesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateItemStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemStatusRequest) Reset() {
	*x = CreateItemStatusRequest{}
	mi := &file_item_item_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemStatusRequest) ProtoMessage() {}

func (x *CreateItemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemStatusRequest.ProtoReflect.Descriptor instead.
func (*CreateItemStatusRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{26}
}

func (x *CreateItemStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateItemStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ItemStatus            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemStatusResponse) Reset() {
	*x = CreateItemStatusResponse{}
	mi := &file_item_item_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemStatusResponse) ProtoMessage() {}

func (x *CreateItemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemStatusResponse.ProtoReflect.Descriptor instead.
func (*CreateItemStatusResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{27}
}

func (x *CreateItemStatusResponse) GetStatus() *ItemStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateItemStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemStatusRequest) Reset() {
	*x = UpdateItemStatusRequest{}
	mi := &file_item_item_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemStatusRequest) ProtoMessage() {}

func (x *UpdateItemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemStatusRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateItemStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateItemStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ItemStatus            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemStatusResponse) Reset() {
	*x = UpdateItemStatusResponse{}
	mi := &file_item_item_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemStatusResponse) ProtoMessage() {}

func (x *UpdateItemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemStatusResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateItemStatusResponse) GetStatus() *ItemStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteItemStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemStatusRequest) Reset() {
	*x = DeleteItemStatusRequest{}
	mi := &file_item_item_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemStatusRequest) ProtoMessage() {}

func (x *DeleteItemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemStatusRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemStatusRequest) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteItemStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteItemStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemStatusResponse) Reset() {
	*x = DeleteItemStatusResponse{}
	mi := &file_item_item_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemStatusResponse) ProtoMessage() {}

func (x *DeleteItemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_item_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemStatusResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemStatusResponse) Descriptor() ([]byte, []int) {
	return file_item_item_proto_rawDescGZIP(), []int{31}
}

var File_item_item_proto protoreflect.FileDescriptor

const file_item_item_proto_rawDesc = "" +
	"\n" +
	"\x0fitem/item.proto\x12\x04item\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa6\x01\n" +
	"\n" +
	"ItemStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9b\x03\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x04 \x01(\tH\x01R\bimageUrl\x88\x01\x01\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tstatus_id\x18\x06 \x01(\tR\bstatusId\x12*\n" +
	"\bcategory\x18\a \x01(\v2\x0e.item.CategoryR\bcategory\x12(\n" +
	"\x06status\x18\b \x01(\v2\x10.item.ItemStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_url\"\xc4\x01\n" +
	"\tItemInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12 \n" +
	"\timage_url\x18\x03 \x01(\tH\x01R\bimageUrl\x88\x01\x01\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tstatus_id\x18\x05 \x01(\tR\bstatusIdB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_image_url\"\xbc\x01\n" +
	"\n" +
	"ItemFilter\x12\x1b\n" +
	"\x06search\x18\x01 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x03 \x01(\tH\x02R\n" +
	"categoryId\x88\x01\x01\x12 \n" +
	"\tstatus_id\x18\x04 \x01(\tH\x03R\bstatusId\x88\x01\x01B\t\n" +
	"\a_searchB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_category_idB\f\n" +
	"\n" +
	"_status_id\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x0fGetItemResponse\x12\x1e\n" +
	"\x04item\x18\x01 \x01(\v2\n" +
	".item.ItemR\x04item\"\xac\x01\n" +
	"\x10ListItemsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12%\n" +
	"\x0esort_direction\x18\x04 \x01(\tR\rsortDirection\x12(\n" +
	"\x06filter\x18\x05 \x01(\v2\x10.item.ItemFilterR\x06filter\"V\n" +
	"\x11ListItemsResponse\x12 \n" +
	"\x05items\x18\x01 \x03(\v2\n" +
	".item.ItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"8\n" +
	"\x11CreateItemRequest\x12#\n" +
	"\x04item\x18\x01 \x01(\v2\x0f.item.ItemInputR\x04item\"4\n" +
	"\x12CreateItemResponse\x12\x1e\n" +
	"\x04item\x18\x01 \x01(\v2\n" +
	".item.ItemR\x04item\"H\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x04item\x18\x02 \x01(\v2\x0f.item.ItemInputR\x04item\"4\n" +
	"\x12UpdateItemResponse\x12\x1e\n" +
	"\x04item\x18\x01 \x01(\v2\n" +
	".item.ItemR\x04item\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteItemResponse\"V\n" +
	"\n" +
	"NameFilter\x12\x1b\n" +
	"\x06search\x18\x01 \x01(\tH\x00R\x06search\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01B\t\n" +
	"\a_searchB\a\n" +
	"\x05_name\"\xb1\x01\n" +
	"\x15ListCategoriesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12%\n" +
	"\x0esort_direction\x18\x04 \x01(\tR\rsortDirection\x12(\n" +
	"\x06filter\x18\x05 \x01(\v2\x10.item.NameFilterR\x06filter\"i\n" +
	"\x16ListCategoriesResponse\x12.\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x0e.item.CategoryR\n" +
	"categories\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"+\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x16CreateCategoryResponse\x12*\n" +
	"\bcategory\x18\x01 \x01(\v2\x0e.item.CategoryR\bcategory\";\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"D\n" +
	"\x16UpdateCategoryResponse\x12*\n" +
	"\bcategory\x18\x01 \x01(\v2\x0e.item.CategoryR\bcategory\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteCategoryResponse\"\xb3\x01\n" +
	"\x17ListItemStatusesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\x12%\n" +
	"\x0esort_direction\x18\x04 \x01(\tR\rsortDirection\x12(\n" +
	"\x06filter\x18\x05 \x01(\v2\x10.item.NameFilterR\x06filter\"i\n" +
	"\x18ListItemStatusesResponse\x12,\n" +
	"\bstatuses\x18\x01 \x03(\v2\x10.item.ItemStatusR\bstatuses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"-\n" +
	"\x17CreateItemStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x18CreateItemStatusResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\v2\x10.item.ItemStatusR\x06status\"=\n" +
	"\x17UpdateItemStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"D\n" +
	"\x18UpdateItemStatusResponse\x12(\n" +
	"\x06status\x18\x01 \x01(\v2\x10.item.ItemStatusR\x06status\")\n" +
	"\x17DeleteItemStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18DeleteItemStatusResponse2\xc6\x02\n" +
	"\vItemService\x126\n" +
	"\aGetItem\x12\x14.item.GetItemRequest\x1a\x15.item.GetItemResponse\x12<\n" +
	"\tListItems\x12\x16.item.ListItemsRequest\x1a\x17.item.ListItemsResponse\x12?\n" +
	"\n" +
	"CreateItem\x12\x17.item.CreateItemRequest\x1a\x18.item.CreateItemResponse\x12?\n" +
	"\n" +
	"UpdateItem\x12\x17.item.UpdateItemRequest\x1a\x18.item.UpdateItemResponse\x12?\n" +
	"\n" +
	"DeleteItem\x12\x17.item.DeleteItemRequest\x1a\x18.item.DeleteItemResponse2\xc5\x02\n" +
	"\x0fCategoryService\x12K\n" +
	"\x0eListCategories\x12\x1b.item.ListCategoriesRequest\x1a\x1c.item.ListCategoriesResponse\x12K\n" +
	"\x0eCreateCategory\x12\x1b.item.CreateCategoryRequest\x1a\x1c.item.CreateCategoryResponse\x12K\n" +
	"\x0eUpdateCategory\x12\x1b.item.UpdateCategoryRequest\x1a\x1c.item.UpdateCategoryResponse\x12K\n" +
	"\x0eDeleteCategory\x12\x1b.item.DeleteCategoryRequest\x1a\x1c.item.DeleteCategoryResponse2\xdf\x02\n" +
	"\x11ItemStatusService\x12Q\n" +
	"\x10ListItemStatuses\x12\x1d.item.ListItemStatusesRequest\x1a\x1e.item.ListItemStatusesResponse\x12Q\n" +
	"\x10CreateItemStatus\x12\x1d.item.CreateItemStatusRequest\x1a\x1e.item.CreateItemStatusResponse\x12Q\n" +
	"\x10UpdateItemStatus\x12\x1d.item.UpdateItemStatusRequest\x1a\x1e.item.UpdateItemStatusResponse\x12Q\n" +
	"\x10DeleteItemStatus\x12\x1d.item.DeleteItemStatusRequest\x1a\x1e.item.DeleteItemStatusResponseb\x06proto3"

var (
	file_item_item_proto_rawDescOnce sync.Once
	file_item_item_proto_rawDescData []byte
)

func file_item_item_proto_rawDescGZIP() []byte {
	file_item_item_proto_rawDescOnce.Do(func() {
		file_item_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_item_proto_rawDesc), len(file_item_item_proto_rawDesc)))
	})
	return file_item_item_proto_rawDescData
}

var file_item_item_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_item_item_proto_goTypes = []any{
	(*Category)(nil),                 // 0: item.Category
	(*ItemStatus)(nil),               // 1: item.ItemStatus
	(*Item)(nil),                     // 2: item.Item
	(*ItemInput)(nil),                // 3: item.ItemInput
	(*ItemFilter)(nil),               // 4: item.ItemFilter
	(*GetItemRequest)(nil),           // 5: item.GetItemRequest
	(*GetItemResponse)(nil),          // 6: item.GetItemResponse
	(*ListItemsRequest)(nil),         // 7: item.ListItemsRequest
	(*ListItemsResponse)(nil),        // 8: item.ListItemsResponse
	(*CreateItemRequest)(nil),        // 9: item.CreateItemRequest
	(*CreateItemResponse)(nil),       // 10: item.CreateItemResponse
	(*UpdateItemRequest)(nil),        // 11: item.UpdateItemRequest
	(*UpdateItemResponse)(nil),       // 12: item.UpdateItemResponse
	(*DeleteItemRequest)(nil),        // 13: item.DeleteItemRequest
	(*DeleteItemResponse)(nil),       // 14: item.DeleteItemResponse
	(*NameFilter)(nil),               // 15: item.NameFilter
	(*ListCategoriesRequest)(nil),    // 16: item.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),   // 17: item.ListCategoriesResponse
	(*CreateCategoryRequest)(nil),    // 18: item.CreateCategoryRequest
	(*CreateCategoryResponse)(nil),   // 19: item.CreateCategoryResponse
	(*UpdateCategoryRequest)(nil),    // 20: item.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil),   // 21: item.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),    // 22: item.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),   // 23: item.DeleteCategoryResponse
	(*ListItemStatusesRequest)(nil),  // 24: item.ListItemStatusesRequest
	(*ListItemStatusesResponse)(nil), // 25: item.ListItemStatusesResponse
	(*CreateItemStatusRequest)(nil),  // 26: item.CreateItemStatusRequest
	(*CreateItemStatusResponse)(nil), // 27: item.CreateItemStatusResponse
	(*UpdateItemStatusRequest)(nil),  // 28: item.UpdateItemStatusRequest
	(*UpdateItemStatusResponse)(nil), // 29: item.UpdateItemStatusResponse
	(*DeleteItemStatusRequest)(nil),  // 30: item.DeleteItemStatusRequest
	(*DeleteItemStatusResponse)(nil), // 31: item.DeleteItemStatusResponse
	(*timestamppb.Timestamp)(nil),    // 32: google.protobuf.Timestamp
}
var file_item_item_proto_depIdxs = []int32{
	32, // 0: item.Category.created_at:type_name -> google.protobuf.Timestamp
	32, // 1: item.Category.updated_at:type_name -> google.protobuf.Timestamp
	32, // 2: item.ItemStatus.created_at:type_name -> google.protobuf.Timestamp
	32, // 3: item.ItemStatus.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: item.Item.category:type_name -> item.Category
	1,  // 5: item.Item.status:type_name -> item.ItemStatus
	32, // 6: item.Item.created_at:type_name -> google.protobuf.Timestamp
	32, // 7: item.Item.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 8: item.GetItemResponse.item:type_name -> item.Item
	4,  // 9: item.ListItemsRequest.filter:type_name -> item.ItemFilter
	2,  // 10: item.ListItemsResponse.items:type_name -> item.Item
	3,  // 11: item.CreateItemRequest.item:type_name -> item.ItemInput
	2,  // 12: item.CreateItemResponse.item:type_name -> item.Item
	3,  // 13: item.UpdateItemRequest.item:type_name -> item.ItemInput
	2,  // 14: item.UpdateItemResponse.item:type_name -> item.Item
	15, // 15: item.ListCategoriesRequest.filter:type_name -> item.NameFilter
	0,  // 16: item.ListCategoriesResponse.categories:type_name -> item.Category
	0,  // 17: item.CreateCategoryResponse.category:type_name -> item.Category
	0,  // 18: item.UpdateCategoryResponse.category:type_name -> item.Category
	15, // 19: item.ListItemStatusesRequest.filter:type_name -> item.NameFilter
	1,  // 20: item.ListItemStatusesResponse.statuses:type_name -> item.ItemStatus
	1,  // 21: item.CreateItemStatusResponse.status:type_name -> item.ItemStatus
	1,  // 22: item.UpdateItemStatusResponse.status:type_name -> item.ItemStatus
	5,  // 23: item.ItemService.GetItem:input_type -> item.GetItemRequest
	7,  // 24: item.ItemService.ListItems:input_type -> item.ListItemsRequest
	9,  // 25: item.ItemService.CreateItem:input_type -> item.CreateItemRequest
	11, // 26: item.ItemService.UpdateItem:input_type -> item.UpdateItemRequest
	13, // 27: item.ItemService.DeleteItem:input_type -> item.DeleteItemRequest
	16, // 28: item.CategoryService.ListCategories:input_type -> item.ListCategoriesRequest
	18, // 29: item.CategoryService.CreateCategory:input_type -> item.CreateCategoryRequest
	20, // 30: item.CategoryService.UpdateCategory:input_type -> item.UpdateCategoryRequest
	22, // 31: item.CategoryService.DeleteCategory:input_type -> item.DeleteCategoryRequest
	24, // 32: item.ItemStatusService.ListItemStatuses:input_type -> item.ListItemStatusesRequest
	26, // 33: item.ItemStatusService.CreateItemStatus:input_type -> item.CreateItemStatusRequest
	28, // 34: item.ItemStatusService.UpdateItemStatus:input_type -> item.UpdateItemStatusRequest
	30, // 35: item.ItemStatusService.DeleteItemStatus:input_type -> item.DeleteItemStatusRequest
	6,  // 36: item.ItemService.GetItem:output_type -> item.GetItemResponse
	8,  // 37: item.ItemService.ListItems:output_type -> item.ListItemsResponse
	10, // 38: item.ItemService.CreateItem:output_type -> item.CreateItemResponse
	12, // 39: item.ItemService.UpdateItem:output_type -> item.UpdateItemResponse
	14, // 40: item.ItemService.DeleteItem:output_type -> item.DeleteItemResponse
	17, // 41: item.CategoryService.ListCategories:output_type -> item.ListCategoriesResponse
	19, // 42: item.CategoryService.CreateCategory:output_type -> item.CreateCategoryResponse
	21, // 43: item.CategoryService.UpdateCategory:output_type -> item.UpdateCategoryResponse
	23, // 44: item.CategoryService.DeleteCategory:output_type -> item.DeleteCategoryResponse
	25, // 45: item.ItemStatusService.ListItemStatuses:output_type -> item.ListItemStatusesResponse
	27, // 46: item.ItemStatusService.CreateItemStatus:output_type -> item.CreateItemStatusResponse
	29, // 47: item.ItemStatusService.UpdateItemStatus:output_type -> item.UpdateItemStatusResponse
	31, // 48: item.ItemStatusService.DeleteItemStatus:output_type -> item.DeleteItemStatusResponse
	36, // [36:49] is the sub-list for method output_type
	23, // [23:36] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_item_item_proto_init() }
func file_item_item_proto_init() {
	if File_item_item_proto != nil {
		return
	}
	file_item_item_proto_msgTypes[2].OneofWrappers = []any{}
	file_item_item_proto_msgTypes[3].OneofWrappers = []any{}
	file_item_item_proto_msgTypes[4].OneofWrappers = []any{}
	file_item_item_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_item_proto_rawDesc), len(file_item_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_item_item_proto_goTypes,
		DependencyIndexes: file_item_item_proto_depIdxs,
		MessageInfos:      file_item_item_proto_msgTypes,
	}.Build()
	File_item_item_proto = out.File
	file_item_item_proto_goTypes = nil
	file_item_item_proto_depIdxs = nil
}
