// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: user/events.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserEvent is every message on the user.events topic. The message key is
// the user id, so one user's events stay in order.
type UserEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique per event; consumers use it to skip events they already handled,
	// since Kafka can deliver a message more than once.
	EventId    string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UserEvent_UserDeleted
	Payload       isUserEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UserEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *UserEvent) GetPayload() isUserEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UserEvent) GetUserDeleted() *UserDeleted {
	if x != nil {
		if x, ok := x.Payload.(*UserEvent_UserDeleted); ok {
			return x.UserDeleted
		}
	}
	return nil
}

type isUserEvent_Payload interface {
	isUserEvent_Payload()
}

type UserEvent_UserDeleted struct {
	UserDeleted *UserDeleted `protobuf:"bytes,10,opt,name=user_deleted,json=userDeleted,proto3,oneof"`
}

func (*UserEvent_UserDeleted) isUserEvent_Payload() {}

// UserDeleted: the user was deleted. The auth-service deletes their login
// and sessions.
type UserDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleted) Reset() {
	*x = UserDeleted{}
	mi := &file_user_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleted) ProtoMessage() {}

func (x *UserDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_user_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleted.ProtoReflect.Descriptor instead.
func (*UserDeleted) Descriptor() ([]byte, []int) {
	return file_user_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserDeleted) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_user_events_proto protoreflect.FileDescriptor

const file_user_events_proto_rawDesc = "" +
	"\n" +
	"\x11user/events.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n" +
	"\tUserEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x126\n" +
	"\fuser_deleted\x18\n" +
	" \x01(\v2\x11.user.UserDeletedH\x00R\vuserDeletedB\t\n" +
	"\apayload\"&\n" +
	"\vUserDeleted\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userIdb\x06proto3"

var (
	file_user_events_proto_rawDescOnce sync.Once
	file_user_events_proto_rawDescData []byte
)

func file_user_events_proto_rawDescGZIP() []byte {
	file_user_events_proto_rawDescOnce.Do(func() {
		file_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_events_proto_rawDesc), len(file_user_events_proto_rawDesc)))
	})
	return file_user_events_proto_rawDescData
}

var file_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_events_proto_goTypes = []any{
	(*UserEvent)(nil),             // 0: user.UserEvent
	(*UserDeleted)(nil),           // 1: user.UserDeleted
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_user_events_proto_depIdxs = []int32{
	2, // 0: user.UserEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: user.UserEvent.user_deleted:type_name -> user.UserDeleted
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_events_proto_init() }
func file_user_events_proto_init() {
	if File_user_events_proto != nil {
		return
	}
	file_user_events_proto_msgTypes[0].OneofWrappers = []any{
		(*UserEvent_UserDeleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_events_proto_rawDesc), len(file_user_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_events_proto_goTypes,
		DependencyIndexes: file_user_events_proto_depIdxs,
		MessageInfos:      file_user_events_proto_msgTypes,
	}.Build()
	File_user_events_proto = out.File
	file_user_events_proto_goTypes = nil
	file_user_events_proto_depIdxs = nil
}
