// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email string `json:"email"`
	// At least 8 characters.
	Password  string `json:"password"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	// E.164, e.g. +31612345678.
	Phone *string `json:"phone,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	// E.164, e.g. +31612345678.
	Phone     *string   `json:"phone,omitempty"`
	AvatarURL *string   `json:"avatarUrl,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type UserConnection struct {
	// Users matching the filter across all pages.
	TotalCount int     `json:"totalCount"`
	Nodes      []*User `json:"nodes"`
}

// Every set field must match as a case-insensitive substring.
type UserFilter struct {
	// Matches any of the name (including first + last), email or phone.
	Search    *string `json:"search,omitempty"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     *string `json:"email,omitempty"`
	Phone     *string `json:"phone,omitempty"`
}

// A user's editable fields. On update every field is replaced, so leaving
// phone or avatarUrl out clears it.
type UserInput struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Email     string  `json:"email"`
	Phone     *string `json:"phone,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
}

type UserOrder struct {
	Field     UserSortField `json:"field"`
	Direction SortDirection `json:"direction"`
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserSortField string

const (
	UserSortFieldFirstName UserSortField = "FIRST_NAME"
	UserSortFieldLastName  UserSortField = "LAST_NAME"
	UserSortFieldEmail     UserSortField = "EMAIL"
	UserSortFieldPhone     UserSortField = "PHONE"
	UserSortFieldCreatedAt UserSortField = "CREATED_AT"
	UserSortFieldUpdatedAt UserSortField = "UPDATED_AT"
)

var AllUserSortField = []UserSortField{
	UserSortFieldFirstName,
	UserSortFieldLastName,
	UserSortFieldEmail,
	UserSortFieldPhone,
	UserSortFieldCreatedAt,
	UserSortFieldUpdatedAt,
}

func (e UserSortField) IsValid() bool {
	switch e {
	case UserSortFieldFirstName, UserSortFieldLastName, UserSortFieldEmail, UserSortFieldPhone, UserSortFieldCreatedAt, UserSortFieldUpdatedAt:
		return true
	}
	return false
}

func (e UserSortField) String() string {
	return string(e)
}

func (e *UserSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserSortField", str)
	}
	return nil
}

func (e UserSortField) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
