package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/jochem11/inventory-manager/services/graphql-gateway/internal/graph/generated"
	"github.com/jochem11/inventory-manager/services/graphql-gateway/internal/graph/model"
)

// User is the resolver for the user field.
func (r *authPayloadResolver) User(ctx context.Context, obj *model.AuthPayload) (*model.User, error) {
	return r.UserResolver.Profile(ctx, obj.UserID)
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (string, error) {
	return r.AuthResolver.Register(ctx, input)
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (bool, error) {
	return r.AuthResolver.VerifyEmail(ctx, token)
}

// ResendVerification is the resolver for the resendVerification field.
func (r *mutationResolver) ResendVerification(ctx context.Context, email string) (bool, error) {
	return r.AuthResolver.ResendVerification(ctx, email)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	return r.AuthResolver.Login(ctx, email, password)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*model.AuthPayload, error) {
	return r.AuthResolver.Refresh(ctx)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	return r.AuthResolver.Logout(ctx)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return r.UserResolver.Me(ctx)
}

// AuthPayload returns generated.AuthPayloadResolver implementation.
func (r *Resolver) AuthPayload() generated.AuthPayloadResolver { return &authPayloadResolver{r} }

type authPayloadResolver struct{ *Resolver }
