package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/jochem11/inventory-manager/services/graphql-gateway/internal/graph/model"
)

// CreateItem is the resolver for the createItem field.
func (r *mutationResolver) CreateItem(ctx context.Context, input model.ItemInput) (*model.Item, error) {
	return r.ItemResolver.Create(ctx, input)
}

// UpdateItem is the resolver for the updateItem field.
func (r *mutationResolver) UpdateItem(ctx context.Context, id string, input model.ItemInput) (*model.Item, error) {
	return r.ItemResolver.Update(ctx, id, input)
}

// DeleteItem is the resolver for the deleteItem field.
func (r *mutationResolver) DeleteItem(ctx context.Context, id string) (string, error) {
	return r.ItemResolver.Delete(ctx, id)
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, name string) (*model.Category, error) {
	return r.ItemResolver.CreateCategory(ctx, name)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, name string) (*model.Category, error) {
	return r.ItemResolver.UpdateCategory(ctx, id, name)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (string, error) {
	return r.ItemResolver.DeleteCategory(ctx, id)
}

// CreateItemStatus is the resolver for the createItemStatus field.
func (r *mutationResolver) CreateItemStatus(ctx context.Context, name string) (*model.ItemStatus, error) {
	return r.ItemResolver.CreateStatus(ctx, name)
}

// UpdateItemStatus is the resolver for the updateItemStatus field.
func (r *mutationResolver) UpdateItemStatus(ctx context.Context, id string, name string) (*model.ItemStatus, error) {
	return r.ItemResolver.UpdateStatus(ctx, id, name)
}

// DeleteItemStatus is the resolver for the deleteItemStatus field.
func (r *mutationResolver) DeleteItemStatus(ctx context.Context, id string) (string, error) {
	return r.ItemResolver.DeleteStatus(ctx, id)
}

// Item is the resolver for the item field.
func (r *queryResolver) Item(ctx context.Context, id string) (*model.Item, error) {
	return r.ItemResolver.Get(ctx, id)
}

// Items is the resolver for the items field.
func (r *queryResolver) Items(ctx context.Context, offset int, limit int, orderBy *model.ItemOrder, filter *model.ItemFilter) (*model.ItemConnection, error) {
	return r.ItemResolver.List(ctx, offset, limit, orderBy, filter)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, offset int, limit int, orderBy *model.NameOrder, filter *model.NameFilter) (*model.CategoryConnection, error) {
	return r.ItemResolver.ListCategories(ctx, offset, limit, orderBy, filter)
}

// ItemStatuses is the resolver for the itemStatuses field.
func (r *queryResolver) ItemStatuses(ctx context.Context, offset int, limit int, orderBy *model.NameOrder, filter *model.NameFilter) (*model.ItemStatusConnection, error) {
	return r.ItemResolver.ListStatuses(ctx, offset, limit, orderBy, filter)
}
